version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  run-tests:
        docker:
          - image: cypress/base:latest
        steps:
          - checkout
          - run:
              name: Install dependencies
              command: npm install
          - run:
              name: Build the app
              command: npm run build
          - run:
              name: Run server
              command: npm run start:dev
          - run:
              name: Run Cypress E2E
              command: npm run test

workflows:
  run-tests:
    jobs:
      - run-tests
